name: Visual Regression Testing

## プルリクエストのスクリーンショットを保存するワークフロー
on:
  pull_request:
    types: [opened, reopened]

jobs:
  reg-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      actions: read # for downloading artifacts
      contents: write # for pushing screenshot-diff to companion branch
      pull-requests: write # for creating a comment on pull requests

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 17

      # Better than caching and/or extensions of actions/setup-java
      - name: Setup Gradle
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
        with:
          gradle-version: wrapper

      - name: create the current snapshot
        run: |
          ./gradlew recordRoborazziDebug --stacktrace
      - name: run reg
        run: |
          yarn run reg-suit run --test