name: Visual Regression Testing2

on:
  pull_request:
    types: [opened, reopened]

jobs:
  reg-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      actions: read # for downloading artifacts
      contents: write # for pushing screenshot-diff to companion branch
      pull-requests: write # for creating a comment on pull requests

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 17
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install, build, and test
        run: |
          npm i
      # Better than caching and/or extensions of actions/setup-java
      - name: Setup Gradle
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
        with:
          gradle-version: wrapper
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull origin ${GITHUB_REF#refs/heads/}
      - name: create the current snapshot
        run: |
          ./gradlew recordRoborazziDebug --stacktrace
      - name: run reg-suit
        run: |
          npx reg-suit run